### ISSUE TITLE
Installing Drupal Commerce

### ISSUE THREAD

**Issue by rjpalermo1** [madalinignisca/drupal-dockerized#1]
Hi, so I've spent all of a couple of days trying to figure out how to create a pre-configured drupal-commerce docker setup.  I really just want to have a docker-compose up that build the image(s) and sets up the drupal-commerce ready to go (for demos) that has an admin, a customer, the sample dummy gateway and a single product.  What I would like is to just provide the docker-compose to a non-technical business person and a few instructions to launch the demo.

I keep getting lost and found this setup from a link you provided in some random blog I found searching for help.  Looking at the way you have everything organized I am imagining (hoping) your setup may be something that can work.

Is what I am looking to do possible?  If this is possible, can I beg for an example or a pointer? 

I've notice that carts like woocommerce and prestashop have literally hundreds of docker repos on git and I was able to stitch together the above for those carts, yet drupal-commerce has only 3 or 4....amazing to me considering I see drupal commerce has almost 100k sites in the wild. 

Thank you in advance for any consideration...

**Comment by madalinignisca** [comment]
Hi @rjpalermo1.
To setup a demo for a non-tech, I would not do the Drupal installation, but I would import a DB dump from a customised demo.

Send me an email if you'd like to develop on the subject more.
